name: Build

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to create GitHub releases

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short $GITHUB_SHA)"

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: 'build --build-cache --daemon' # use the daemon here so the rest of the process is faster
          generate-job-summary: false
          gradle-home-cache-includes: |
            caches
            jdks
            notifications
            wrapper

	  - name: Changelog
		id: changelog
		uses: mikepenz/release-changelog-builder-action@v5
		with:
		  configuration: ./.github/json/config-latest.json
		  fromTag: latest-${{ github.ref_name }}
		  toTag: ${{ github.ref }}
		  fetchViaCommits: true
		  failOnError: false
		- name: Release Latest
			        uses: andelf/nightly-release@46e2d5f80828ecc5c2c3c819eb31186a7cf2156c
			        with:
			          tag_name: latest-${{ github.ref_name }}
			          name: '${{ github.ref_name }}-${{ steps.ver.outputs.version}} SNAPSHOT $$'
			          prerelease: true
			          body: |
			            The latest build of NepFactory
			            Please report any [issues](https://github.com/NepJr/nfmod).
			            ${{ steps.changelog.outputs.changelog }}
			          files: build/libs/*.jar